# Generated by Django 4.2.6 on 2023-10-24 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='historicalapplication',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Заказ', 'verbose_name_plural': 'historical Заказы'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='application',
            name='auth_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.authuser', verbose_name='Офицант'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='application',
            name='number_cab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.office', verbose_name='Выберите срочность'),
        ),
        migrations.AlterField(
            model_name='application',
            name='worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'labs'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Повар'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='auth_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.authuser', verbose_name='Офицант'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='description',
            field=models.TextField(verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='number_cab',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.office', verbose_name='Выберите срочность'),
        ),
        migrations.AlterField(
            model_name='historicalapplication',
            name='worker',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'groups__name': 'labs'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Повар'),
        ),
        migrations.AlterField(
            model_name='office',
            name='number',
            field=models.CharField(default='', max_length=9, verbose_name='Срочность'),
        ),
    ]
